export const SEND_WEBSOCKET_MESSAGE = 'SEND_WEBSOCKET_MESSAGE';
export const SOCKET_MESSAGE_RECEIVED = 'SOCKET_MESSAGE_RECEIVED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
