export const SEND_WEBSOCKET_MESSAGE = 'SEND_WEBSOCKET_MESSAGE';
export const SOCKET_MESSAGE_RECEIVED = 'SOCKET_MESSAGE_RECEIVED';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
export const SET_ALL_AVAILABLE_USERS = 'SET_ALL_AVAILABLE_USERS';

export const BAN_USER = 'BAN_USER';
export const UNBAN_USER = 'UNBAN_USER';
export const MUTE_USER = 'MUTE_USER';
export const UNMUTE_USER = 'UNMUTE_USER';
